### ISSUE TITLE
p72 is open

### ISSUE THREAD

**Issue by echavemann** [northwesternfintech/2024QuantInternships#5]

**Comment by ayushgun** [comment]
P72 is open for summer 2023 afaik, not summer 2024.

**Comment by echavemann** [comment]
> P72 is open for summer 2023 afaik, not summer 2024.

Nah it's 2024

https://www.google.com/search?q=point72+careers&rlz=1CDGOYI_enUS966US966&oq=point72+careers&aqs=chrome..69i57.6287j0j4&hl=en-US&sourceid=chrome-mobile&ie=UTF-8&dlnr=1&sei=bEAfZPTwDdiqptQPiY6U2AY#dlnr=1&fpstate=tldetail&htidocid=NAAs0OTfwVoAAAAAAAAAAA%3D%3D&htiq=point72%20careers&htivrt=jobs

**Comment by ayushgun** [comment]
Only the "Investment Analyst" position has a 2024 internship open. QD/QR is still 2023 only. 
Source: https://careers.point72.com/?experience=internships

**Comment by echavemann** [comment]
get what you mean. good point.

**Comment by echavemann** [comment]
ty!
